# Generated by Django 5.0.6 on 2024-05-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Launch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.URLField()),
                ("details", models.TextField(null=True)),
                ("article_link", models.URLField(null=True)),
                ("reddit_link", models.URLField(null=True)),
                ("wikipedia_link", models.URLField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("S", "Success"), ("U", "Upcoming"), ("F", "Failed")],
                        max_length=1,
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
