# Generated by Django 5.0.6 on 2024-05-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spacex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="launch",
            name="image",
            field=models.URLField(null=True),
        ),
    ]
